---
- hosts: all
  become_user: root
  tasks:
    - name: install kind
      shell: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.12.0/kind-linux-amd64
        chmod +x ./kind
        mv ./kind /usr/local/bin/kind
    - name: install clusterctl
      shell: |
        curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/clusterctl-linux-amd64 -o clusterctl
        chmod +x ./clusterctl
        mv ./clusterctl /usr/local/bin/clusterctl
    - name: install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
    - name: install docker
      yum:
        name: docker
        state: present
    - name: enable docker in systemd
      systemd:
        enabled: yes
        state: started
        name: docker

# Create kind cluster
- hosts: all
  become_user: root
  tasks:
    - name: get if kind cluster exists
      shell: "kind get clusters | grep kind"
      register: result
      ignore_errors: true
    - name: create kind cluster
      shell: kind create cluster
      when: result.rc != 0

# Install latest KubeVirt and CDI in the kubernetes cluster
- hosts: all
  become_user: root
  tasks:
    - name: install latest KubeVirt
      environment:
        VERSION: v0.52.0
      shell: |
        kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt-operator.yaml
        kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt-cr.yaml
    - name: install latest CDI 
      environment:
        VERSION: v1.47.0
      shell: |
        kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
        kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml
